# Generated by Django 4.1 on 2024-06-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_role_sysmenu_userinfo_role_sys_menus"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
