# Generated by Django 4.2.11 on 2024-06-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_userinfo_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="image",
            field=models.CharField(default="", max_length=128),
        ),
    ]
