# Generated by Django 4.2.11 on 2024-06-16 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_order2menu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order2menu",
            name="user",
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.userinfo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order2menu",
            name="order",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.order",
            ),
        ),
    ]
