# Generated by Django 4.2.11 on 2024-06-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_remove_order2menu_user_order_order2menu_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.IntegerField(default=0),
        ),
    ]
