# Generated by Django 4.2.11 on 2024-06-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_order_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="time",
            field=models.CharField(max_length=128),
        ),
    ]
